darickc/MMM-BackgroundSlideshow

- MMM-BackgroundSlideshow.js
Moved this.updateImage(); from resume: function to socketNotificationReceived: to prevent changing background image on resume as often happens with modules like MMM-Carousel.
> Prevent changing background image on resume

- MMM-BackgroundSlideshow.js
- README.md
It appears the `horizontalGradient` isn't being used anywhere in the code, so this pull request removes it.
> Remove unused horizontalGradient config

- MMM-BackgroundSlideshow.js
Previously only values of 6 & 8 were handled.
Testing: tested manually with images from https://github.com/recurser/exif-orientation-examples.
This CL is not perfect, as CSS transforms also apply to the containing div's dimensions esp. flipping width/height on rotation, but it's better than the previous state.
> Handle all values of EXIF orientation

- MMM-BackgroundSlideshow.js
Build backgroundImage style using double quotes to fix a bug where a paths containing single quotes not displayed (e.g. a directory called "John's photos").
Notably paths containing double quotes are escaped by the underlying code so this change displays them as well.
> Correct display image paths that include single quote character

- BackgroundSlideshow.css
- MMM-BackgroundSlideshow.js
- README.md
Add a showmageInfo configuration option to toggle behavior, default is false.
Currently the image file name is displayed, the parent directory is also shown if recursiveSubDirectories is set.
In the future, this area may be used to display image capture time or other EXIF information.
> Display image name in a panel at the bottom right of the screen

- MMM-BackgroundSlideshow.js
- README.md
Closes #34
Changes:
- Implement BACKGROUNDSLIDESHOW_PREVIOUS to back up one image.
- Comment out Log messages for notifications so they don't flood the browser console (clock sends one once per second).
- Cleanup: use early returns in updateImage() to reduce nesting - no behavior change.
> Implement BACKGROUNDSLIDESHOW_PREVIOUS to go back to previous image

- MMM-BackgroundSlideshow.js
- README.md
Modify the behavior of showImageInfo so that instead of blindly showing only the parent directory, the relative path is now shown.
e.g. for a configuration of imagePaths = ['foo'] and an image at 'foo/bar/baz/image.jpg':
* old behavior: 'baz/image.jpg' was displayed.
* now 'bar/baz/image.jpg' is displayed.
Other cleanup in this cl:
- Split out update of imageInfo into. its own function.
- Make indent and spacing between functions uniform.
Tested manually.
> showImageInfo shows relative path when recurseSubdirectories is true

- MMM-BackgroundSlideshow.js
- README.md
- node_helper.js
Changes:
* Instead of parsing config for each image file, create a Set() and use that to check image file extensions.
* Add .jpeg to default set of accepted image file types.
* ES6: Change some instances of var to const/let in node_helper.js.
* Remove some unneeded definitions of 'self'.
* Minor spelling correction and whitespace fixes.
Tested manually.
> Use Set() for image file filtering and add .jpeg to default extensions

- MMM-BackgroundSlideshow.js
Chrome 81 (released on April 7th) added native support for rotating images based on EXIF. Disable CSS fix so the image display correctly on newer Chrome versions with the fix.
References:
* https://www.chromestatus.com/feature/6313474512650240
* https://crbug.com/158753
* https://paul.kinlan.me/correct-image-orientation-for-images-chrome-81/
* https://www.chromestatus.com/features/schedule
> Disable EXIF orientation CSS fix for browsers with native support

- MMM-BackgroundSlideshow.js
- README.md
- node_helper.js
This fixes Issue #26.
Add new excludePaths config option, directory names must match exactly.
> Add support for excluding named paths when scanning for images

- MMM-BackgroundSlideshow.js
- README.md
Hi,
i use the module in a picture frame with pages.
I saw in the code that you commented out the update of the image after the module got resumed. I re-added it but with an config option. The default behavior stays the same but i can re-activate it in my setup.
I also updated the Readme.
It would be great if merge it to your code.
> added configuration option to change the image directly after resume

- MMM-BackgroundSlideshow.js
no need to encodeURI local files. It even causes issues with filenames that have single quotations marks in their name.
> removed encodeURI

- .prettierrc.json
- BackgroundSlideshow.css
- MMM-BackgroundSlideshow.js
- node_helper.js
Hi! Thanks for the great module. 
I made some adaptions to make it run more smoothly: 
1. Added a custom loading handler for the images in express. (Before all images were loaded without caching, leading to loading the image three times (one for `img.src`, one for `EXIF.getTags()` and one for css `url()`), now the static images are loaded with a cache header of 1 hour and thus only loaded once. 
2. I also added a random scrolling for panorama pictures, now they do not only scroll from top to bottom (or left to right) but also the other way around. 
3. Lastly I formatted the files with prettier, but you don't have to use it, just makes it easier for me and more consistent. 
I would be glad if you want to merge :)
> Better loading performance and better panorama scrolling

- MMM-BackgroundSlideshow.js
I want to use the BACKGROUNDSLIDESHOW_URLS notification but found out that it didnt work. 
After digging around in the code, i found that i```imageList``` and ```imageIndex``` were set but never used to present pictures.
The following codes uses both variables in the ```updateImage``` function until the imageList is empty, whereafter it will default on to the normal paths that have been set in the config.
> Fix to make BACKGROUNDSLIDESHOW_URLS work

- node_helper.js
- package.json
instead of system libraries jimp uses javascript functions to process the images; cause of this no recompile jimp is a little bit slower than sharp but no recompile is needed.
as i am not a javascript guru please review and test the change. i am open minded for changes and input
> replaced sharp call with jimp call at image resize

- node_helper.js
- package.json
Added code to rotate jpg/jpeg images based on the exif orientation information before they get resized with Jimp functions.
Jimp removes every Exif information so the orientation change needs to be performed before any Jimp function is called.
> Rotate images before resize

- MMM-BackgroundSlideshow.js
- README.md
pull request to incorporate @MacG-DD code from #106 for a config option to remove the file extension when displaying `name` in `imageInfo`
changed the code slightly to follow the naming pattern of related config options
> add imageInfoNoFileExt config option (resolves #106)

- MMM-BackgroundSlideshow.js
- node_helper.js
- package.json
When using MagicMirror server only/client only strategy as described in the [official docs](https://docs.magicmirror.builders/getting-started/installation.html#server-only), restarting the server node leaves the client node "zombie" due the server isn't available to retrieve configuration from the client again.
The error log is:
```
...
[INFO]  BACKGROUNDSLIDESHOW_NEXT_IMAGE
[LOG]   undefined
[ERROR] Whoops! There was an uncaught exception...
[ERROR] TypeError: Cannot read properties of undefined (reading 'imagePaths')
at Class.gatherImageList (/opt/magic_mirror/modules/MMM-BackgroundSlideshow/node_helper.js:112:32)
at Class.getNextImage (/opt/magic_mirror/modules/MMM-BackgroundSlideshow/node_helper.js:146:12)
at Class.socketNotificationReceived …
```
> Fixed bug on distributed instance (serveronly and client modes

- MMM-BackgroundSlideshow.js
Instead of trimming at the first "." in a file name, it trims from the last.  Preserving file names such as "M.C. Escher - Some Woodblock Print.jpg", etc.
(This is my first time editing a file on github, I hope I'm doing this right.)
> Correct file extension trimming

- node_helper.js
Since moving to Sharp for image resizing the image overlay no longer works. This fixes it.
> Retain metadata on image resize so that Image Info overlay still works

- node_helper.js
I am using a script to sync a lot of family photos from Dropbox to my rpi every morning. In my family photos there are some photos I dont want to be displayed on my MM, hence this commit enables me to put a `excludeImages.txt` in every folder that has one or several photos that I dont want MM to recognize. 
a `excludeImages.txt` can be put in every sub-directory that this module is scanning, and is just a text file with a list of image names to exclude. 
Example: 
This is one of the folders I sync from dropbox: 
```
rclone sync dropbox: /home/kalle/Pictures/ \
--include "Camera Uploads/Spara/*.jpg" \
--include "Camera Uploads/Spara/excludeImages.txt" \
--ignore-case -P
```
and the `excludeImages.txt` would contain something like: 
```
imagename1
image 2
nude photo of me
```
Notice the …
> Exclude images

- .gitignore
- README.md
- node_helper.js
this is a pr for changing the  location of the `filesShownTracker.txt` since the docker version didn't like the home-dir... 
see [reported issue](https://github.com/darickc/MMM-BackgroundSlideshow/issues/164)
> Bugfix pr162
